# Generated by Django 2.2.5 on 2019-11-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_hint',
            field=models.CharField(default='', max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_answer',
            field=models.CharField(default='', max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='', max_length=1000000),
            preserve_default=False,
        ),
    ]
