# Generated by Django 2.2.5 on 2019-11-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20191107_0326'),
        ('game', '0003_auto_20191106_1134'),
    ]

    operations = [
    ]
